console.log(Math.E)
console.log(Math.PI)
var n = 4.489
console.log(Math.abs(n))
console.log(Math.floor(n))
console.log(Math.ceil(n))
console.log(Math.round(n))

console.log(Math.max(232,435,534))
console.log(Math.min(23432,1232,56554))
console.log(Math.pow(2,3))
console.log(Math.pow(3,4))
console.log(Math.sqrt(9))
console.log(Math.random())
console.log(Math.random() * 50 + 1)
console.log(Math.round(Math.random() * 50 + 1))